client_id = "4a43d1c4309a6f8a7474c76840f86eaa"
name = "Seleric-Tracker"
application_url = "https://tracker.seleric.cloud"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
  topics = ["app/uninstalled"]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = ["app/scopes_update"]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = ["orders/create"]
  uri = "/api/webhooks/orders-create"

  [[webhooks.subscriptions]]
  topics = ["orders/paid"]
  uri = "/api/webhooks/orders-paid"

  [[webhooks.subscriptions]]
  topics = ["orders/updated"]
  uri = "/api/webhooks/orders-updated"

  [[webhooks.subscriptions]]
  topics = ["customers/create"]
  uri = "/api/webhooks/customers-create"

[access_scopes]
scopes = "read_products,read_orders,read_customers,read_customer_events,write_pixels"

[auth]
redirect_urls = ["https://tracker.seleric.cloud/auth/callback"]
